# Generated by Django 5.1.4 on 2025-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("status", models.CharField(default="Исправен", max_length=50)),
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="inventoryrequest",
            name="id",
        ),
        migrations.AddField(
            model_name="inventoryrequest",
            name="request_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
