# Generated by Django 5.1.4 on 2025-01-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0002_inventoryitem_remove_inventoryrequest_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryrequest",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
