# Generated by Django 5.1.4 on 2025-01-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0003_inventoryrequest_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
