# Generated by Django 5.1.4 on 2025-01-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0006_purchaseplan_usagereport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
