# Generated by Django 5.1.6 on 2025-02-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0008_alter_inventoryitem_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={
                "verbose_name": "предмет инвентаря",
                "verbose_name_plural": "Предметы инвентаря",
            },
        ),
        migrations.AlterModelOptions(
            name="inventoryrequest",
            options={
                "verbose_name": "запрос на инвентарь",
                "verbose_name_plural": "Запросы на инвентарь",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseplan",
            options={
                "verbose_name": "план закупки",
                "verbose_name_plural": "Планы закупок",
            },
        ),
        migrations.AlterModelOptions(
            name="usagereport",
            options={
                "verbose_name": "отчет об использовании",
                "verbose_name_plural": "Отчеты об использовании",
            },
        ),
        migrations.AddField(
            model_name="usagereport",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="status",
            field=models.CharField(
                default="Исправен", max_length=50, verbose_name="Статус"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="inventoryrequest",
            name="item_name",
            field=models.CharField(max_length=255, verbose_name="Название предмета"),
        ),
        migrations.AlterField(
            model_name="inventoryrequest",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="inventoryrequest",
            name="status",
            field=models.CharField(
                default="В ожидании", max_length=50, verbose_name="Статус"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="invpage.inventoryitem",
                verbose_name="Инвентарь",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseplan",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="invpage.inventoryitem",
                verbose_name="Инвентарь",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseplan",
            name="planned_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Планируемая цена"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseplan",
            name="planned_supplier",
            field=models.CharField(
                max_length=255, verbose_name="Планируемый поставщик"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseplan",
            name="purchase_date",
            field=models.DateField(verbose_name="Дата покупки"),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="invpage.inventoryitem",
                verbose_name="Инвентарь",
            ),
        ),
        migrations.AlterField(
            model_name="usagereport",
            name="notes",
            field=models.TextField(verbose_name="Заметки"),
        ),
    ]
