# Generated by Django 5.1.6 on 2025-02-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0009_alter_inventoryitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryrequest",
            name="quantity_of_all",
            field=models.PositiveIntegerField(default=0, verbose_name="Всего"),
        ),
    ]
