# Generated by Django 5.1.6 on 2025-02-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0010_inventoryrequest_quantity_of_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryrequest",
            name="item_id",
            field=models.PositiveIntegerField(default=0, verbose_name="id"),
        ),
    ]
