# Generated by Django 5.1.6 on 2025-02-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0011_inventoryrequest_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryrequest",
            name="quantity_item",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество предметов"
            ),
        ),
    ]
