# Generated by Django 5.1.6 on 2025-02-08 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0012_inventoryrequest_quantity_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryrequest",
            name="item_id",
        ),
        migrations.RemoveField(
            model_name="inventoryrequest",
            name="quantity_item",
        ),
        migrations.AddField(
            model_name="inventoryrequest",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="invpage.inventoryitem",
            ),
        ),
    ]
