# Generated by Django 5.1.6 on 2025-02-08 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0013_remove_inventoryrequest_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryrequest",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="invpage.inventoryitem"
            ),
        ),
    ]
