# Generated by Django 5.1.6 on 2025-02-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0014_alter_inventoryrequest_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryrequest",
            name="quantity_of_all",
        ),
    ]
