# Generated by Django 5.1.6 on 2025-02-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0015_remove_inventoryrequest_quantity_of_all"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryrequest",
            name="item_name",
        ),
    ]
