# Generated by Django 5.1.6 on 2025-02-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invpage", "0016_remove_inventoryrequest_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryrequest",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="invpage.inventoryitem",
                verbose_name="Предмет",
            ),
        ),
    ]
