# Generated by Django 5.1.4 on 2025-01-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_userregistration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregistration",
            name="token_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
